(function(){if(!window.I18N)return;
window.I18N.register('ar',{s_start:'ابدأ الحكاية ←',s_title:'رجال البحر في أكتوبر',s_subtitle:'المعركة التي لم يرها معظم الناس',s_back:'← الصفحة الرئيسية',s_school:'مدرسة المنار القومية للغات للبنات',s_page:'حكايات أكتوبر',s_scroll:'انزل لتبدأ الحكاية ↓',s_author:'إعداد وتقديم',s_reaction_title:'إيه رأيك في الحكاية؟',s_reaction_help:'اختار إعجابك، وكمان رد فعل واحد يعبّر عن رأيك. من غير أسماء أو تعليقات مكتوبة.',s_sources:'المصادر والمراجع',s_disclaimer:'تمت إعادة صياغة المعلومات بأسلوب مناسب للصف الأول الإعدادي، مع الاعتماد على المصادر المذكورة.'});
window.I18N.register('en',{s_start:'Start the story →',s_title:'Men of the Sea in October',s_subtitle:'The battle most people never saw',s_back:'← Home',s_school:'Al-Manar National Language School for Girls',s_page:'October Stories',s_scroll:'Scroll to begin the story ↓',s_author:'Prepared and presented by',s_reaction_title:'What do you think of this story?',s_reaction_help:'Choose a like and one reaction that reflects your opinion. No names or written comments.',s_sources:'Sources and references',s_disclaimer:'The information has been rewritten for first-year preparatory students, based on the listed sources.'});
window.I18N.register('fr',{s_start:'Commencer le récit →',s_title:'Les hommes de la mer en octobre',s_subtitle:'La bataille que la plupart des gens n’ont pas vue',s_back:'← Accueil',s_school:'École nationale de langues Al-Manar pour filles',s_page:'Récits d’octobre',s_scroll:'Faites défiler pour commencer ↓',s_author:'Préparé et présenté par',s_reaction_title:'Que pensez-vous de ce récit ?',s_reaction_help:'Choisissez un J’aime et une réaction qui exprime votre avis. Sans nom ni commentaire écrit.',s_sources:'Sources et références',s_disclaimer:'Les informations ont été reformulées pour des élèves de première année préparatoire à partir des sources citées.'});
window.I18N.register('it',{s_start:'Inizia il racconto →',s_title:'Gli uomini del mare in ottobre',s_subtitle:'La battaglia che la maggior parte delle persone non ha visto',s_back:'← Home',s_school:'Scuola nazionale linguistica Al-Manar per ragazze',s_page:'Racconti d’ottobre',s_scroll:'Scorri per iniziare il racconto ↓',s_author:'Preparato e presentato da',s_reaction_title:'Cosa ne pensi di questo racconto?',s_reaction_help:'Scegli un Mi piace e una reazione che esprima la tua opinione. Senza nomi o commenti scritti.',s_sources:'Fonti e riferimenti',s_disclaimer:'Le informazioni sono state rielaborate per studenti del primo anno della scuola media sulla base delle fonti indicate.'});
window.I18N.register('ar',{"s_like":"❤️ أعجبتني","s_liked":"تم تسجيل إعجابك","s_reaction_loved":"حكاية ومجهود مميز","s_reaction_unknown":"حكاية لم أكن أعرفها من قبل","s_reaction_inspiring":"حكاية ملهمة","s_reaction_more":"أحب أقرأ حكايات تانية"});
window.I18N.register('en',{"s_like":"❤️ I like this","s_liked":"Like recorded","s_reaction_loved":"A story and effort worth celebrating","s_reaction_unknown":"A story I had not heard before","s_reaction_inspiring":"An inspiring story","s_reaction_more":"I’d like to read more stories"});
window.I18N.register('fr',{"s_like":"❤️ J’aime","s_liked":"J’aime enregistré","s_reaction_loved":"Un récit et un travail remarquables","s_reaction_unknown":"Un récit que je ne connaissais pas","s_reaction_inspiring":"Un récit inspirant","s_reaction_more":"J’aimerais lire d’autres récits"});
window.I18N.register('it',{"s_like":"❤️ Mi piace","s_liked":"Mi piace registrato","s_reaction_loved":"Un racconto e un lavoro notevoli","s_reaction_unknown":"Un racconto che non conoscevo","s_reaction_inspiring":"Un racconto ispiratore","s_reaction_more":"Vorrei leggere altri racconti"});
window.I18N.register('ar',{"r_feedback_exists":"سجّلت رد فعل لهذه الحكاية بالفعل من هذا المتصفح.","r_like_exists":"سجّلت إعجابك بهذه الحكاية بالفعل.","r_saving":"جارٍ تسجيل اختيارك…","r_saved":"شكرًا لك! تم تسجيل اختيارك.","r_already_saved":"الاختيار مسجّل بالفعل لهذه الحكاية.","r_saved_count_error":"اختيارك اتسجل، لكن تعذر تحديث العدادات الآن. حدّث الصفحة لاحقًا.","r_save_error":"ماقدرناش نسجل الاختيار الآن. جرّب تاني بعد قليل.","r_counts_error":"عدادات التفاعل غير متاحة مؤقتًا. جرّب تحديث الصفحة.","r_choice_aria":"اختر رد فعلك على الحكاية"});
window.I18N.register('en',{"r_feedback_exists":"You have already submitted a reaction to this story from this browser.","r_like_exists":"You have already liked this story.","r_saving":"Saving your choice…","r_saved":"Thank you! Your choice has been recorded.","r_already_saved":"Your choice has already been recorded for this story.","r_saved_count_error":"Your choice was saved, but the counts could not be refreshed. Please reload later.","r_save_error":"We couldn’t save your choice right now. Please try again shortly.","r_counts_error":"Reactions are temporarily unavailable. Please refresh the page.","r_choice_aria":"Choose your reaction to the story"});
window.I18N.register('fr',{"r_feedback_exists":"Vous avez déjà réagi à cette histoire depuis ce navigateur.","r_like_exists":"Vous avez déjà aimé cette histoire.","r_saving":"Enregistrement de votre choix…","r_saved":"Merci ! Votre choix a été enregistré.","r_already_saved":"Votre choix a déjà été enregistré pour cette histoire.","r_saved_count_error":"Votre choix a été enregistré, mais les compteurs n’ont pas pu être actualisés. Réessayez plus tard.","r_save_error":"Impossible d’enregistrer votre choix pour le moment. Réessayez bientôt.","r_counts_error":"Les réactions sont temporairement indisponibles. Actualisez la page.","r_choice_aria":"Choisissez votre réaction à cette histoire"});
window.I18N.register('it',{"r_feedback_exists":"Hai già inviato una reazione a questa storia da questo browser.","r_like_exists":"Hai già messo Mi piace a questa storia.","r_saving":"Salvataggio della scelta…","r_saved":"Grazie! La tua scelta è stata registrata.","r_already_saved":"La tua scelta è già stata registrata per questa storia.","r_saved_count_error":"La scelta è stata salvata, ma non è stato possibile aggiornare i conteggi. Riprova più tardi.","r_save_error":"Non è stato possibile salvare la scelta. Riprova tra poco.","r_counts_error":"Le reazioni non sono temporaneamente disponibili. Aggiorna la pagina.","r_choice_aria":"Scegli la tua reazione alla storia"});
window.I18N.apply();
function syncSplash(){var lang=window.I18N.lang();var splash=document.querySelector('.story-splash');if(!splash)return;var h=splash.querySelector('h1'),p=splash.querySelector('p'),b=splash.querySelector('button');if(h)h.textContent=window.I18N.t('s_title');if(p)p.textContent=window.I18N.t('s_subtitle');if(b)b.textContent=window.I18N.t('s_start');splash.style.direction=lang==='ar'?'rtl':'ltr';}
document.addEventListener('site-language-change',syncSplash);document.addEventListener('DOMContentLoaded',syncSplash);setTimeout(syncSplash,0);
})();