(function(){if(!window.I18N)return;
window.I18N.register('ar',{s_start:'ابدأ الحكاية ←',s_title:'العقل قبل السلاح',s_subtitle:'كيف فتحت المياه طريق العبور',s_back:'← الصفحة الرئيسية',s_school:'مدرسة المنار القومية للغات للبنات',s_page:'حكايات أكتوبر',s_scroll:'انزل لتبدأ الحكاية ↓',s_author:'إعداد وتقديم',s_reaction_title:'إيه رأيك في الحكاية؟',s_reaction_help:'اختار إعجابك، وكمان رد فعل واحد يعبّر عن رأيك. من غير أسماء أو تعليقات مكتوبة.',s_sources:'المصادر والمراجع',s_disclaimer:'تمت إعادة صياغة المعلومات بأسلوب الطالبة، ولم تُنسخ نصوص المصادر.'});
window.I18N.register('en',{s_start:'Start the story →',s_title:'Brains Before Weapons',s_subtitle:'How water opened the way for the crossing',s_back:'← Home',s_school:'Al-Manar National Language School for Girls',s_page:'October Stories',s_scroll:'Scroll to begin the story ↓',s_author:'Prepared and presented by',s_reaction_title:'What do you think of this story?',s_reaction_help:'Choose a like and one reaction that reflects your opinion. No names or written comments.',s_sources:'Sources and references',s_disclaimer:'The information has been rewritten in the student’s own style; source texts were not copied.'});
window.I18N.register('fr',{s_start:'Commencer le récit →',s_title:'L’intelligence avant les armes',s_subtitle:'Comment l’eau a ouvert la voie au passage',s_back:'← Accueil',s_school:'École nationale de langues Al-Manar pour filles',s_page:'Récits d’octobre',s_scroll:'Faites défiler pour commencer ↓',s_author:'Préparé et présenté par',s_reaction_title:'Que pensez-vous de ce récit ?',s_reaction_help:'Choisissez un J’aime et une réaction qui exprime votre avis. Sans nom ni commentaire écrit.',s_sources:'Sources et références',s_disclaimer:'Les informations ont été reformulées dans le style de l’élève, sans copier les textes des sources.'});
window.I18N.register('it',{s_start:'Inizia il racconto →',s_title:'L’ingegno prima delle armi',s_subtitle:'Come l’acqua aprì la strada all’attraversamento',s_back:'← Home',s_school:'Scuola nazionale linguistica Al-Manar per ragazze',s_page:'Racconti d’ottobre',s_scroll:'Scorri per iniziare il racconto ↓',s_author:'Preparato e presentato da',s_reaction_title:'Cosa ne pensi di questo racconto?',s_reaction_help:'Scegli un Mi piace e una reazione che esprima la tua opinione. Senza nomi o commenti scritti.',s_sources:'Fonti e riferimenti',s_disclaimer:'Le informazioni sono state rielaborate nello stile della studentessa senza copiare i testi delle fonti.'});
window.I18N.register('ar',{"s_like":"❤️ أعجبتني","s_liked":"تم تسجيل إعجابك","s_reaction_loved":"حكاية ومجهود مميز","s_reaction_unknown":"حكاية لم أكن أعرفها من قبل","s_reaction_inspiring":"حكاية ملهمة","s_reaction_more":"أحب أقرأ حكايات تانية"});
window.I18N.register('en',{"s_like":"❤️ I like this","s_liked":"Like recorded","s_reaction_loved":"A story and effort worth celebrating","s_reaction_unknown":"A story I had not heard before","s_reaction_inspiring":"An inspiring story","s_reaction_more":"I’d like to read more stories"});
window.I18N.register('fr',{"s_like":"❤️ J’aime","s_liked":"J’aime enregistré","s_reaction_loved":"Un récit et un travail remarquables","s_reaction_unknown":"Un récit que je ne connaissais pas","s_reaction_inspiring":"Un récit inspirant","s_reaction_more":"J’aimerais lire d’autres récits"});
window.I18N.register('it',{"s_like":"❤️ Mi piace","s_liked":"Mi piace registrato","s_reaction_loved":"Un racconto e un lavoro notevoli","s_reaction_unknown":"Un racconto che non conoscevo","s_reaction_inspiring":"Un racconto ispiratore","s_reaction_more":"Vorrei leggere altri racconti"});
window.I18N.apply();
function syncSplash(){var lang=window.I18N.lang();var splash=document.querySelector('.story-splash');if(!splash)return;var h=splash.querySelector('h1'),p=splash.querySelector('p'),b=splash.querySelector('button');if(h)h.textContent=window.I18N.t('s_title');if(p)p.textContent=window.I18N.t('s_subtitle');if(b)b.textContent=window.I18N.t('s_start');splash.style.direction=lang==='ar'?'rtl':'ltr';}
document.addEventListener('site-language-change',syncSplash);document.addEventListener('DOMContentLoaded',syncSplash);setTimeout(syncSplash,0);
})();