(function(){if(!window.I18N)return;
window.I18N.register('ar',{s_author_name:'نوردين محمد جمال',s_footer_date:'أكتوبر 1973',src1:'الهيئة العامة للاستعلامات المصرية — انتصارات أكتوبر والضربة الجوية',src2:'وزارة الدفاع المصرية — وثائق حرب أكتوبر 1973: الضربة الجوية والتمهيد النيراني وعبور قناة السويس',src3:'وزارة الأوقاف المصرية — الشهيد عاطف السادات',src4:'بوابة الأهرام — السرب 82 ومشاركته في الضربة الجوية الأولى'});
window.I18N.register('en',{s_author_name:'Nourdeen Mohamed Gamal',s_footer_date:'October 1973',src1:'Egypt State Information Service — October victories and the air strike',src2:'Egyptian Ministry of Defence — October 1973 War documents: the air strike, the artillery preparation, and the Suez Canal crossing',src3:'Egyptian Ministry of Awqaf — Martyr Atef El-Sadat',src4:'Al-Ahram Gate — Squadron 82 and its part in the first air strike'});
window.I18N.register('fr',{s_author_name:'Nourdeen Mohamed Gamal',s_footer_date:'Octobre 1973',src1:'Service d’information de l’État égyptien — Les victoires d’octobre et la frappe aérienne',src2:'Ministère égyptien de la Défense — Documents de la guerre d’octobre 1973 : la frappe aérienne, la préparation d’artillerie et le franchissement du canal de Suez',src3:'Ministère égyptien des Awqaf — Le martyr Atef El-Sadat',src4:'Bawabat Al-Ahram — L’escadron 82 et sa participation à la première frappe aérienne'});
window.I18N.register('it',{s_author_name:'Nourdeen Mohamed Gamal',s_footer_date:'Ottobre 1973',src1:'Servizio d’informazione dello Stato egiziano — Le vittorie d’ottobre e l’attacco aereo',src2:'Ministero della Difesa egiziano — Documenti della guerra dell’ottobre 1973: l’attacco aereo, la preparazione di artiglieria e l’attraversamento del Canale di Suez',src3:'Ministero egiziano degli Awqaf — Il martire Atef El-Sadat',src4:'Bawabat Al-Ahram — Il 82º squadrone e la sua partecipazione al primo attacco aereo'});

window.I18N.register('ar',{g_kicker:'وجوه من ذاكرة أكتوبر',g_title:'شهداء حملوا أسماءهم إلى التاريخ',g_intro:'تحتفظ المصادر المنشورة بصور بعض الأبطال وأسمائهم. نعرض هنا صورتين موثقتين، مع احترام اختلاف الروايات التاريخية وعدم الادعاء بأنهما القائمة الكاملة لكل شهداء الضربة.',g_label:'من شهداء اليوم الأول',g_atef_name:'النقيب طيار محمد عاطف أنور السادات',g_atef_text:'شارك في الضربة الجوية الأولى يوم 6 أكتوبر 1973، ولم تعد طائرته بعد تنفيذ المهمة.',g_zakaria_name:'الطيار زكريا كمال',g_zakaria_text:'قائد تشكيل من طائرات سوخوي 7، وتذكر تقارير صحفية استشهاده خلال مهمة الضربة الأولى قرب مطار المليز.',g_photo_source1:'مصدر الصورة وترخيصها',g_photo_source2:'مصدر الصورة والتفاصيل',g_note:'تنبيه للدقة: تختلف بعض المصادر في الرتبة والتفاصيل وترتيب الاستشهاد؛ لذلك نذكر الأسماء دون الجزم بترتيب «أول شهيد»، ولا نعرض هذه الصور على أنها سجل كامل لجميع الشهداء.'});
window.I18N.register('en',{g_kicker:'Faces remembered in October',g_title:'Pilots whose names live on',g_intro:'Published sources preserve photographs and accounts of some of these pilots. Here are two sourced portraits; they are not presented as a complete list of everyone who died in the strike.',g_label:'Among the fallen on the first day',g_atef_name:'Flight Lieutenant Mohamed Atef Anwar El-Sadat',g_atef_text:'He took part in the first air strike on 6 October 1973 and did not return after carrying out his mission.',g_zakaria_name:'Pilot Zakaria Kamal',g_zakaria_text:'A leader of a Sukhoi-7 formation; press accounts report that he was killed during the first-strike mission near El-Meliz airfield.',g_photo_source1:'Photo source and licensing',g_photo_source2:'Photo source and report',g_note:'Historical note: sources differ on rank, details, and who was first to die. The names are shown without claiming a definitive order, and these portraits are not a complete casualty register.'});
window.I18N.register('fr',{g_kicker:'Des visages dans la mémoire d’Octobre',g_title:'Des pilotes dont les noms demeurent',g_intro:'Des sources publiées conservent les portraits et les récits de certains pilotes. Voici deux portraits sourcés, sans prétendre présenter la liste complète des morts de la frappe.',g_label:'Parmi les morts du premier jour',g_atef_name:'Lieutenant pilote Mohamed Atef Anwar El-Sadat',g_atef_text:'Il a participé à la première frappe aérienne le 6 octobre 1973 et n’est pas revenu après sa mission.',g_zakaria_name:'Le pilote Zakaria Kamal',g_zakaria_text:'Chef d’une formation de Sukhoi-7 ; des articles de presse rapportent sa mort pendant la mission près de l’aérodrome d’El-Meliz.',g_photo_source1:'Source et licence de la photo',g_photo_source2:'Source de la photo et du récit',g_note:'Note historique : les sources divergent sur le grade, certains détails et l’identité du premier mort. Les noms sont présentés sans ordre définitif ; ces portraits ne constituent pas une liste complète des victimes.'});
window.I18N.register('it',{g_kicker:'Volti ricordati nell’Ottobre',g_title:'Piloti i cui nomi restano',g_intro:'Le fonti pubblicate conservano fotografie e racconti di alcuni piloti. Qui presentiamo due ritratti con fonti, senza affermare che siano l’elenco completo dei caduti nell’attacco.',g_label:'Tra i caduti del primo giorno',g_atef_name:'Tenente pilota Mohamed Atef Anwar El-Sadat',g_atef_text:'Partecipò al primo attacco aereo il 6 ottobre 1973 e non fece ritorno dopo aver compiuto la missione.',g_zakaria_name:'Il pilota Zakaria Kamal',g_zakaria_text:'Comandante di una formazione di Sukhoi-7; resoconti giornalistici riferiscono che morì durante la missione vicino all’aeroporto di El-Meliz.',g_photo_source1:'Fonte e licenza della foto',g_photo_source2:'Fonte della foto e del resoconto',g_note:'Nota storica: le fonti differiscono sul grado, sui dettagli e su chi sia stato il primo a morire. I nomi sono riportati senza stabilire un ordine definitivo; questi ritratti non sono un elenco completo delle vittime.'});

window.I18N.apply();
})();
